// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Content;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.TikTok.OpenApiClient.V2.Post.Publish
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\post\publish
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublishRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The content property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Content.ContentRequestBuilder Content
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The creator_info property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Creator_infoRequestBuilder Creator_info
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Creator_infoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inbox property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.InboxRequestBuilder Inbox
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.InboxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The video property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.VideoRequestBuilder Video
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.VideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.PublishRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublishRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.PublishRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublishRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
