// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Query;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\post\publish\creator_info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Creator_infoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The query property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Query.QueryRequestBuilder Query
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Creator_infoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Creator_infoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/creator_info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Creator_info.Creator_infoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Creator_infoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/creator_info", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
