// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishCreatorInfoQueryResponseData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Returns true if the creator sets the comment interaction to &quot;No one&quot; in their privacy setting.</summary>
        public bool? CommentDisabled { get; set; }
        /// <summary>The URL of the TikTok creator&apos;s avatar with a TTL of 2 hours.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorAvatarUrl { get; set; }
#nullable restore
#else
        public string CreatorAvatarUrl { get; set; }
#endif
        /// <summary>The nickname of the TikTok creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorNickname { get; set; }
#nullable restore
#else
        public string CreatorNickname { get; set; }
#endif
        /// <summary>The unique ID of the TikTok creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorUsername { get; set; }
#nullable restore
#else
        public string CreatorUsername { get; set; }
#endif
        /// <summary>Returns true if the creator account is private or they set the Duet interaction to &quot;No one&quot; in their privacy setting. IGNORE if your client only sends photo media through this API.</summary>
        public bool? DuetDisabled { get; set; }
        /// <summary>The longest video duration in seconds that the TikTok creator can post. Different users have different maximum video-duration privileges. Developers should use this field to stop video posts that are too long. IGNORE if your client only sends photo media through this API.</summary>
        public int? MaxVideoPostDurationSec { get; set; }
        /// <summary>If the TikTok creator account is public, the available options are: PUBLIC_TO_EVERYONE MUTUAL_FOLLOW_FRIENDS SELF_ONLY If the TikTok creator account is private, the available options are: FOLLOWER_OF_CREATOR MUTUAL_FOLLOW_FRIENDS SELF_ONLY</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PrivacyLevelOptions { get; set; }
#nullable restore
#else
        public List<string> PrivacyLevelOptions { get; set; }
#endif
        /// <summary>Returns true if the creator account is private or they set the Stitch interaction to &quot;No one&quot; in their privacy setting. IGNORE if your client only sends photo media through this API.</summary>
        public bool? StitchDisabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishCreatorInfoQueryResponseData"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishCreatorInfoQueryResponseData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishCreatorInfoQueryResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishCreatorInfoQueryResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishCreatorInfoQueryResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment_disabled", n => { CommentDisabled = n.GetBoolValue(); } },
                { "creator_avatar_url", n => { CreatorAvatarUrl = n.GetStringValue(); } },
                { "creator_nickname", n => { CreatorNickname = n.GetStringValue(); } },
                { "creator_username", n => { CreatorUsername = n.GetStringValue(); } },
                { "duet_disabled", n => { DuetDisabled = n.GetBoolValue(); } },
                { "max_video_post_duration_sec", n => { MaxVideoPostDurationSec = n.GetIntValue(); } },
                { "privacy_level_options", n => { PrivacyLevelOptions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "stitch_disabled", n => { StitchDisabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("comment_disabled", CommentDisabled);
            writer.WriteStringValue("creator_avatar_url", CreatorAvatarUrl);
            writer.WriteStringValue("creator_nickname", CreatorNickname);
            writer.WriteStringValue("creator_username", CreatorUsername);
            writer.WriteBoolValue("duet_disabled", DuetDisabled);
            writer.WriteIntValue("max_video_post_duration_sec", MaxVideoPostDurationSec);
            writer.WriteCollectionOfPrimitiveValues<string>("privacy_level_options", PrivacyLevelOptions);
            writer.WriteBoolValue("stitch_disabled", StitchDisabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
