// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishVideoInitRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The post_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo? PostInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo PostInfo { get; set; }
#endif
        /// <summary>The source_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo? SourceInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo SourceInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishVideoInitRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "post_info", n => { PostInfo = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo.CreateFromDiscriminatorValue); } },
                { "source_info", n => { SourceInfo = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo>("post_info", PostInfo);
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo>("source_info", SourceInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
