// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    /// <summary>
    /// The post information
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostV2PostPublishContentInitRequestPostInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only works for post_mode = DIRECT POST. If set to true, recommended music will be automatically added to photos, and users can later choose to change the post&apos;s music in TikTok if they prefer other music.</summary>
        public bool? AutoAddMusic { get; set; }
        /// <summary>Only works for post_mode = DIRECT POST. Set to true if the content is a paid partnership to promote a third-party business.</summary>
        public bool? BrandContentToggle { get; set; }
        /// <summary>Only works for post_mode = DIRECT POST. Set to true if this content is promoting the creator&apos;s own business.</summary>
        public bool? BrandOrganicToggle { get; set; }
        /// <summary>The post description. The maximum length for photo posts is 4000 in UTF-16 runes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Only works for post_mode = DIRECT POST. If set to true, other TikTok users will not be allowed to make comments on this post.</summary>
        public bool? DisableComment { get; set; }
        /// <summary>Enum of: PUBLIC_TO_EVERYONE MUTUAL_FOLLOW_FRIENDS FOLLOWER_OF_CREATOR SELF_ONLY The provided value must match one of the privacy_level_options returned in the /creator_info/query/ API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrivacyLevel { get; set; }
#nullable restore
#else
        public string PrivacyLevel { get; set; }
#endif
        /// <summary>The post title. The maximum length for photo posts is 90 in UTF-16 runes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishContentInitRequestPostInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_add_music", n => { AutoAddMusic = n.GetBoolValue(); } },
                { "brand_content_toggle", n => { BrandContentToggle = n.GetBoolValue(); } },
                { "brand_organic_toggle", n => { BrandOrganicToggle = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "disable_comment", n => { DisableComment = n.GetBoolValue(); } },
                { "privacy_level", n => { PrivacyLevel = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_add_music", AutoAddMusic);
            writer.WriteBoolValue("brand_content_toggle", BrandContentToggle);
            writer.WriteBoolValue("brand_organic_toggle", BrandOrganicToggle);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("disable_comment", DisableComment);
            writer.WriteStringValue("privacy_level", PrivacyLevel);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
