// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishInboxVideoInitResponse : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseData? DataEscaped { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseData DataEscaped { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseError Error { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponse"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishInboxVideoInitResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { DataEscaped = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseData>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseData.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseError>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseError.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseData>("data", DataEscaped);
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishInboxVideoInitResponseError>("error", Error);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
