// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishContentInitRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Set to `true` if the photo is AI generated content. If set, the photo will be labeled with an AI-generated tag in the description.</summary>
        public bool? IsAigc { get; set; }
        /// <summary>Currently only PHOTO is allowed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaType { get; set; }
#nullable restore
#else
        public string MediaType { get; set; }
#endif
        /// <summary>The post information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo? PostInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo PostInfo { get; set; }
#endif
        /// <summary>Enum of: DIRECT POST: Directly post the content to TikTok user&apos;s account. MEDIA_UPLOAD: Upload content to TikTok for users to complete the post using TikTok&apos;s editing flow. Users will receive an inbox notification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostMode { get; set; }
#nullable restore
#else
        public string PostMode { get; set; }
#endif
        /// <summary>The media source information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestSourceInfo? SourceInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestSourceInfo SourceInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequest"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishContentInitRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is_aigc", n => { IsAigc = n.GetBoolValue(); } },
                { "media_type", n => { MediaType = n.GetStringValue(); } },
                { "post_info", n => { PostInfo = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo.CreateFromDiscriminatorValue); } },
                { "post_mode", n => { PostMode = n.GetStringValue(); } },
                { "source_info", n => { SourceInfo = n.GetObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestSourceInfo>(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestSourceInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is_aigc", IsAigc);
            writer.WriteStringValue("media_type", MediaType);
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestPostInfo>("post_info", PostInfo);
            writer.WriteStringValue("post_mode", PostMode);
            writer.WriteObjectValue<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishContentInitRequestSourceInfo>("source_info", SourceInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
