// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishStatusFetchResponseData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of bytes downloaded (1-indexed) for PULL_FROM_URL</summary>
        public long? DownloadedBytes { get; set; }
        /// <summary>Refer to the fail_reason table to see whether the issue is with the developer, the TikTok creator, or TikTok APIs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailReason { get; set; }
#nullable restore
#else
        public string FailReason { get; set; }
#endif
        /// <summary>post_id is returned only if the post is published for public viewership and has been approved by the TikTok moderation process. Creators may use the uploaded content draft to create multiple pieces of content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? PublicalyAvailablePostId { get; set; }
#nullable restore
#else
        public List<long?> PublicalyAvailablePostId { get; set; }
#endif
        /// <summary>The following are the available statuses: PROCESSING_UPLOAD : Only available for FILE_UPLOAD . Indicates that the upload is in process. PROCESSING_DOWNLOAD : Only available for PULL_FROM_URL . Indicates that the download from the URL is in process. SEND_TO_USER_INBOX : Only available when you choose to upload content . Indicates that a notification has been sent to creator&apos;s inbox to complete the draft post using TikTok&apos;s editing flow. PUBLISH_COMPLETE : For the Direct Post , it indicates that the content has been posted. For the Upload Content, it indicates that the user has clicked on the inbox notification and has successfully posted the media using TikTok editing flow. FAILED : Indicates that an error has occurred and the entire process has failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The number of bytes uploaded (1-indexed) for FILE_UPLOAD</summary>
        public long? UploadedBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishStatusFetchResponseData"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishStatusFetchResponseData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishStatusFetchResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishStatusFetchResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishStatusFetchResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "downloaded_bytes", n => { DownloadedBytes = n.GetLongValue(); } },
                { "fail_reason", n => { FailReason = n.GetStringValue(); } },
                { "publicaly_available_post_id", n => { PublicalyAvailablePostId = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "uploaded_bytes", n => { UploadedBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("downloaded_bytes", DownloadedBytes);
            writer.WriteStringValue("fail_reason", FailReason);
            writer.WriteCollectionOfPrimitiveValues<long?>("publicaly_available_post_id", PublicalyAvailablePostId);
            writer.WriteStringValue("status", Status);
            writer.WriteLongValue("uploaded_bytes", UploadedBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
