// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishVideoInitRequestPostInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Set to true if the video is a paid partnership to promote a third-party business.</summary>
        public bool? BrandContentToggle { get; set; }
        /// <summary>Set to true if this video is promoting the creator&apos;s own business.</summary>
        public bool? BrandOrganicToggle { get; set; }
        /// <summary>If set to true, other TikTok users will not be allowed to make comments on this post. The TikTok server disables comments for users who set the Comments permission to &quot;No one&quot; in their privacy setting.</summary>
        public bool? DisableComment { get; set; }
        /// <summary>If set to true, other TikTok users will not be allowed to make Duets using this post. The TikTok server disables Duets for private accounts and those who set the Duet permission to &quot;No one&quot; in their privacy setting.</summary>
        public bool? DisableDuet { get; set; }
        /// <summary>If set to true, other TikTok users will not be allowed to make Stitches using this post. The TikTok server disables Stitches for private accounts and those who set the Stitch permission to &quot;No one&quot; in their privacy setting.</summary>
        public bool? DisableStitch { get; set; }
        /// <summary>Set to true if the video is AI generated content. If set, the video will be labelled with Creator labeled as AI-generated tag in video&apos;s description.</summary>
        public bool? IsAigc { get; set; }
        /// <summary>Enum of: PUBLIC_TO_EVERYONE MUTUAL_FOLLOW_FRIENDS FOLLOWER_OF_CREATOR SELF_ONLY The provided value must match one of the privacy_level_options returned in the /creator_info/query/ API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrivacyLevel { get; set; }
#nullable restore
#else
        public string PrivacyLevel { get; set; }
#endif
        /// <summary>The video caption. Hashtags (#) and mentions (@) will be matched, or deliminated by spaces or new lines. The maximum length is 2200 in UTF-16 runes. If not specified, the ticket post will not have any captions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Specifies which frame (measured in milli-seconds) will be used as the video cover. If not set, or the specified value is invalid, the cover is set to the first frame of the uploaded video.</summary>
        public int? VideoCoverTimestampMs { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishVideoInitRequestPostInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestPostInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brand_content_toggle", n => { BrandContentToggle = n.GetBoolValue(); } },
                { "brand_organic_toggle", n => { BrandOrganicToggle = n.GetBoolValue(); } },
                { "disable_comment", n => { DisableComment = n.GetBoolValue(); } },
                { "disable_duet", n => { DisableDuet = n.GetBoolValue(); } },
                { "disable_stitch", n => { DisableStitch = n.GetBoolValue(); } },
                { "is_aigc", n => { IsAigc = n.GetBoolValue(); } },
                { "privacy_level", n => { PrivacyLevel = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "video_cover_timestamp_ms", n => { VideoCoverTimestampMs = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("brand_content_toggle", BrandContentToggle);
            writer.WriteBoolValue("brand_organic_toggle", BrandOrganicToggle);
            writer.WriteBoolValue("disable_comment", DisableComment);
            writer.WriteBoolValue("disable_duet", DisableDuet);
            writer.WriteBoolValue("disable_stitch", DisableStitch);
            writer.WriteBoolValue("is_aigc", IsAigc);
            writer.WriteStringValue("privacy_level", PrivacyLevel);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("video_cover_timestamp_ms", VideoCoverTimestampMs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
