// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TikTok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostV2PostPublishVideoInitRequestSourceInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The size of the chunk in bytes.</summary>
        public long? ChunkSize { get; set; }
        /// <summary>Choose from: PULL_FROM_URL FILE_UPLOAD Learn about the limitations for these file transmission methods .</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The total number of chunks.</summary>
        public long? TotalChunkCount { get; set; }
        /// <summary>The size of the to-be-uploaded video file in bytes.</summary>
        public long? VideoSize { get; set; }
        /// <summary>A public-accessible URL from which the TikTok server will pull to retrieve the video resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoUrl { get; set; }
#nullable restore
#else
        public string VideoUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo"/> and sets the default values.
        /// </summary>
        public PostV2PostPublishVideoInitRequestSourceInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequestSourceInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chunk_size", n => { ChunkSize = n.GetLongValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "total_chunk_count", n => { TotalChunkCount = n.GetLongValue(); } },
                { "video_size", n => { VideoSize = n.GetLongValue(); } },
                { "video_url", n => { VideoUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("chunk_size", ChunkSize);
            writer.WriteStringValue("source", Source);
            writer.WriteLongValue("total_chunk_count", TotalChunkCount);
            writer.WriteLongValue("video_size", VideoSize);
            writer.WriteStringValue("video_url", VideoUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
