// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.Video;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\post\publish\inbox
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InboxRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The video property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.Video.VideoRequestBuilder Video
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.Video.VideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.InboxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InboxRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/inbox", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Inbox.InboxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InboxRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/inbox", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
