// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.Fetch;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\post\publish\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fetch property</summary>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.Fetch.FetchRequestBuilder Fetch
        {
            get => new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.Fetch.FetchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
