// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.TikTok.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\post\publish\video\init\
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmptyPathSegmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/video/init/", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/post/publish/video/init/", rawUrl)
        {
        }
        /// <summary>
        /// PostV2PostPublishVideoInit
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse?> PostAsync(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse> PostAsync(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue },
                { "5XX", global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse>(requestInfo, global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// PostV2PostPublishVideoInit
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.TikTok.OpenApiClient.Models.PostV2PostPublishVideoInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init.EmptyPathSegmentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init.EmptyPathSegmentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.TikTok.OpenApiClient.V2.Post.Publish.Video.Init.EmptyPathSegmentRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
